# Generated by Django 4.1.5 on 2023-02-24 13:09

from django.db import migrations
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_alter_user_managers"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user", managers=[("objects", users.models.CustomUserManager()),],
        ),
    ]
